# -*- coding: utf-8 -*-
"""aplicacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hEV1BC9pJMAGm9h_6dJ5aVulYVpjHrGp
"""

import streamlit as st

# Titulo de la aplicación
st.title("Calculadora Simple - Suma de Dos Números")

# Entrada de los dos números
num1 = st.number_input("Ingrese el primer número:", value=0.0)
num2 = st.number_input("Ingrese el segundo número:", value=0.0)

# Botón para calcular la suma
if st.button("Calcular"):
    suma = num1 + num2
    st.success(f"La suma de {num1} y {num2} es: {suma}"